### ISSUE TITLE
Error reading SSH protocol banner error

### ISSUE THREAD

**Issue by R3zk0n** [0xricksanchez/like-dbg#59] opened 2022-08-22 10:25 UTC
**Describe the bug**
Building like-dbg throws error Reading SSH protocol banner halting the build of the application.

**To Reproduce**
1. Running the start-kgdb.py script runs up to like_kbuilder_x86_64:latest (build_image:53)
2. Then throws an error saying Error reading SSH protocol. I have tried this on a VPS and Virtual Machine 
3. Ive also used native python, venv python from 3.6 to 3.10.

**Expected behavior**
Python script to spawn a kernel gdb/gef session with tmux

**Screenshots**
![image](https://user-images.githubusercontent.com/7919239/185899405-f03bccb6-8d6a-41ac-bed4-83643b5c803f.png)

**Comment by 0xricksanchez** [comment] 2022-08-22 11:04
Hi @R3zk0n

Thanks for the report. That looks like it should not happen. Interestingly enough, a colleague of mine just encountered the same behavior on a Fedora system. However, it seems like you're running an Ubuntu. Is this an Ubuntu 22.04?

When this earlier with my colleague, it was working fine on my MANJARO system. I'll investigate this ASAP :)

Sorry for the inconvenience rn

**Comment by R3zk0n** [comment] 2022-08-22 11:34
No worries! I am on ubuntu 22.04, I also tried with a Debian system and a other ubuntu VPS, same sort of issue as well as a Mac running monterey however i noticed that the bug tracker had some issues with Mac,

**Comment by 0xricksanchez** [comment] 2022-08-22 11:39
That's some good info already. I'll set up an Ubuntu 22.04 box and will debug this ASAP. If it ends up running there I'd guess it runs fine on Debian as well.
The problem is hopefully easily resolved.

As for the Apple Hardware, it may work on the Intel ones, but it heavily depends on how you set up your APFS. If you already have one of those M1 Macs I'd suspect everything breaks. I don't have the hardware to debug for these at the moment.

**Comment by 0xricksanchez** [comment] 2022-08-22 14:46
This seems to be introduced due to a race condition here:

[```python
            self.container = self.client.containers.run(
                self.image,
                volumes=[f"{Path.cwd()}:{self.docker_mnt}"],
                ports={"22/tcp": self.ssh_fwd_port},
                detach=True,
                tty=True,
            )
            self.init_ssh()
```](https://github.com/0xricksanchez/like-dbg/blob/main/src/kernel_builder.py#L100)

**Comment by 0xricksanchez** [comment] 2022-08-22 16:04
@R3zk0n I hope the merge to main fixed it. The error is no longer happening in my VM after the changes. Please let me know how it's working for you.

**Comment by R3zk0n** [comment] 2022-08-23 00:03
Hi @0xricksanchez It appears to be fixed in one way but not in a other, however this might be due to I am using SSH to my VPS and testing it on that. 

![image](https://user-images.githubusercontent.com/7919239/186040284-b7eaa501-fa7a-4020-baa3-819c85e1989a.png)

Both docker images are created like_dbg_base and like_kbuilder_x86. The error appears to be on init_ssh:56. 

Could this be since im using SSH to the VPS ?

**Comment by 0xricksanchez** [comment] 2022-08-23 05:52
@R3zk0n That's not good :(. SSH is generally not a problem, what might come into play here is maybe the latency to your VPS as well as what specs it has. Can you give me the specs of yours (CPUs, RAM) so I can rent some similar one for testing?

**Comment by 0xricksanchez** [comment] 2022-08-23 06:18
I just grabbed 2 GB RAM / 2 vCPU VPS to test this out and I can confirm the error still occurs on a low-specced machine. Would you be so kind to test whether changing the `connect_timeout` option in `src/docker_runner.py` (line 45) from *200* ⇾ *1000* helps in your case? It seemed to have worked wonders in my case

**Comment by 0xricksanchez** [comment] 2022-08-23 15:52
Should be fixed. Could not reproduce with latest main branch. Leaving this open for confirmation.

**Comment by 0xricksanchez** [comment] 2022-08-24 08:31
@R3zk0n I will consider this issue fixed as I cannot reproduce it anymore, neither in my locale VMs nor on my VPS. You are welcome to open another issue if you're still encountering this.

Thanks for bringing this to my attention

**Closed by 0xricksanchez** 2022-08-24 08:31 UTC
Labels: bug, high-prio

**Comment by R3zk0n** [comment] 2022-08-29 04:28
Hi, Sorry for the delay i just returned from a trip. So i tried to build it again, everything goes well until here. 

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/7919239/187121303-5296bb85-c423-4b13-85f3-fb44ecd7bf01.png">


Some stats I am root on a  Linnode VPS that has a 6 Cores and 16 GB of Ram. So shouldn't have any issues.

**Comment by 0xricksanchez** [comment] 2022-08-29 06:26
That's an issue when running as root on the host, due to having a non-root user trying to create files/directories within a mounted volume. I'll ship a fix for that. :sweat: 

Alternatively, if you want to get it up and running ASAP just create a new non-root user on that VPS.

As this is a separate issue I'll open a new ticket for that
